{
  "schema_version": "1.6.3",
  "id": "CVE-2014-9601",
  "details": "Pillow before 2.7.0 allows remote attackers to cause a denial of service via a compressed text chunk in a PNG image that has a large size when it is decompressed.",
  "aliases": [],
  "related": [],
  "published": "2015-01-16T00:00:00Z",
  "modified": "2015-01-16T00:00:00Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:14.04:LTS",
        "name": "pillow",
        "purl": "pkg:deb/ubuntu/pillow@2.3.0-1ubuntu3.4?arch=src?distro=trusty"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.3.0-1ubuntu3.4"
            }
          ]
        }
      ],
      "versions": [
        "2.2.1-1ubuntu2",
        "2.2.1-2ubuntu1",
        "2.2.1-3ubuntu2",
        "2.2.1-3ubuntu3",
        "2.2.1-3ubuntu4",
        "2.2.1-3ubuntu6",
        "2.3.0-1ubuntu1",
        "2.3.0-1ubuntu2",
        "2.3.0-1ubuntu3",
        "2.3.0-1ubuntu3.2",
        "2.3.0-1ubuntu3.3"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-imaging": "2.3.0-1ubuntu3.4",
            "python-imaging-compat": "2.3.0-1ubuntu3.4",
            "python-imaging-dbg": "2.3.0-1ubuntu3.4",
            "python-imaging-doc": "2.3.0-1ubuntu3.4",
            "python-imaging-sane": "2.3.0-1ubuntu3.4",
            "python-imaging-sane-dbg": "2.3.0-1ubuntu3.4",
            "python-imaging-tk": "2.3.0-1ubuntu3.4",
            "python-imaging-tk-dbg": "2.3.0-1ubuntu3.4",
            "python-pil": "2.3.0-1ubuntu3.4",
            "python-pil-dbg": "2.3.0-1ubuntu3.4",
            "python-pil-dbgsym": "2.3.0-1ubuntu3.4",
            "python-pil-doc": "2.3.0-1ubuntu3.4",
            "python-pil.imagetk": "2.3.0-1ubuntu3.4",
            "python-pil.imagetk-dbg": "2.3.0-1ubuntu3.4",
            "python-pil.imagetk-dbgsym": "2.3.0-1ubuntu3.4",
            "python-sane": "2.3.0-1ubuntu3.4",
            "python-sane-dbg": "2.3.0-1ubuntu3.4",
            "python-sane-dbgsym": "2.3.0-1ubuntu3.4",
            "python3-imaging": "2.3.0-1ubuntu3.4",
            "python3-imaging-dbg": "2.3.0-1ubuntu3.4",
            "python3-imaging-sane": "2.3.0-1ubuntu3.4",
            "python3-imaging-sane-dbg": "2.3.0-1ubuntu3.4",
            "python3-imaging-tk": "2.3.0-1ubuntu3.4",
            "python3-imaging-tk-dbg": "2.3.0-1ubuntu3.4",
            "python3-pil": "2.3.0-1ubuntu3.4",
            "python3-pil-dbg": "2.3.0-1ubuntu3.4",
            "python3-pil-dbgsym": "2.3.0-1ubuntu3.4",
            "python3-pil.imagetk": "2.3.0-1ubuntu3.4",
            "python3-pil.imagetk-dbg": "2.3.0-1ubuntu3.4",
            "python3-pil.imagetk-dbgsym": "2.3.0-1ubuntu3.4",
            "python3-sane": "2.3.0-1ubuntu3.4",
            "python3-sane-dbg": "2.3.0-1ubuntu3.4",
            "python3-sane-dbgsym": "2.3.0-1ubuntu3.4"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "low"
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2014-9601"
    },
    {
      "type": "REPORT",
      "url": "https://www.djangoproject.com/weblog/2015/jan/02/pillow-security-release/"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/python-pillow/Pillow/pull/1060"
    },
    {
      "type": "REPORT",
      "url": "http://pillow.readthedocs.org/releasenotes/2.7.0.html"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-3090-2"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-3090-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-3230-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-3229-1"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2014-9601"
    }
  ]
}