{
  "schema_version": "1.6.3",
  "id": "CVE-2020-1736",
  "details": "A flaw was found in Ansible Engine when a file is moved using atomic_move primitive as the file mode cannot be specified. This sets the destination files world-readable if the destination file does not exist and if the file exists, the file could be changed to have less restrictive permissions before the move. This could lead to the disclosure of sensitive data. All versions in 2.7.x, 2.8.x and 2.9.x branches are believed to be vulnerable.",
  "aliases": [],
  "related": [],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N"
    }
  ],
  "published": "2020-03-16T16:15:00Z",
  "modified": "2020-03-16T16:15:00Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:14.04:LTS",
        "name": "ansible"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "1.1+dfsg-1",
        "1.3.4+dfsg-1",
        "1.4.0+dfsg-1",
        "1.4.1+dfsg-1",
        "1.4.3+dfsg-1",
        "1.4.4+dfsg-1",
        "1.5.4+dfsg-1",
        "1.5.4+dfsg-1ubuntu0.1~esm2"
      ]
    },
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:16.04:LTS",
        "name": "ansible"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "1.9.2+dfsg-2",
        "1.9.4-1",
        "2.0.0.2-2",
        "2.0.0.2-2ubuntu1",
        "2.0.0.2-2ubuntu1.1",
        "2.0.0.2-2ubuntu1.2",
        "2.0.0.2-2ubuntu1.3",
        "2.0.0.2-2ubuntu1.3+esm1",
        "2.0.0.2-2ubuntu1.3+esm2"
      ]
    },
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:18.04:LTS",
        "name": "ansible"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "2.3.1.0+dfsg-2",
        "2.5.0+dfsg-1",
        "2.5.1+dfsg-1",
        "2.5.1+dfsg-1ubuntu0.1",
        "2.5.1+dfsg-1ubuntu0.1+esm1",
        "2.5.1+dfsg-1ubuntu0.1+esm2"
      ]
    },
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "ansible"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "2.8.3+dfsg-1",
        "2.8.6+dfsg-1",
        "2.9.2+dfsg-1",
        "2.9.4+dfsg-1",
        "2.9.6+dfsg-1"
      ]
    },
    {
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "ansible"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "2.10.7+merged+base+2.10.8+dfsg-1"
      ]
    },
    {
      "package": {
        "ecosystem": "Ubuntu:24.04:LTS",
        "name": "ansible"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "7.7.0+dfsg-1",
        "7.7.0+dfsg-3",
        "9.2.0+dfsg-0ubuntu4",
        "9.2.0+dfsg-0ubuntu5"
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2020-1736"
    },
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1802124"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2020-1736"
    }
  ]
}