{
  "schema_version": "1.6.3",
  "id": "CVE-2016-4807",
  "details": "(Web2py versions 2.14.5 and below was affected by Reflected XSS vulnera ...)",
  "aliases": [],
  "related": [],
  "published": "2024-08-12T00:00:00Z",
  "modified": "2024-08-12T00:00:00Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:16.04:LTS",
        "name": "web2py"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "1.99.7-1",
        "2.12.3-1",
        "2.12.3-1ubuntu0.1"
      ]
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2016-4807"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2016-4807"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/web2py/web2py/issues/1585"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/web2py/web2py/commit/51c3b633fe7ad647bc3013e899c1e3a910362dd1"
    }
  ]
}