{
  "id": "USN-4961-2",
  "summary": "python-pip vulnerability",
  "details": "USN-4961-1 fixed a vulnerability in pip. This update provides the\ncorresponding updates for Ubuntu 14.04 ESM, Ubuntu 16.04 ESM and\nUbuntu 18.04 ESM.\n\nOriginal advisory details:\n\n It was discovered that pip incorrectly handled unicode separators in git\n references. A remote attacker could possibly use this issue to install a\n different revision on a repository.\n",
  "aliases": [],
  "related": [
    "CVE-2021-3572"
  ],
  "published": "2022-05-19T14:07:08.398355Z",
  "modified": "2022-05-19T14:07:08.398355Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:14.04:LTS",
        "name": "python-pip"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.5.4-1ubuntu4+esm1"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-pip": "1.5.4-1ubuntu4+esm1",
            "python-pip-whl": "1.5.4-1ubuntu4+esm1",
            "python3-pip": "1.5.4-1ubuntu4+esm1"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:18.04:LTS",
        "name": "python-pip"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "9.0.1-2.3~ubuntu1.18.04.5+esm2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-pip": "9.0.1-2.3~ubuntu1.18.04.5+esm2",
            "python-pip-whl": "9.0.1-2.3~ubuntu1.18.04.5+esm2",
            "python3-pip": "9.0.1-2.3~ubuntu1.18.04.5+esm2"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:16.04:LTS",
        "name": "python-pip"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "8.1.1-2ubuntu0.6+esm2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-pip": "8.1.1-2ubuntu0.6+esm2",
            "python-pip-whl": "8.1.1-2ubuntu0.6+esm2",
            "python3-pip": "8.1.1-2ubuntu0.6+esm2"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-4961-2"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-3572"
    }
  ]
}