{
  "id": "USN-5200-1",
  "summary": "python3.7, python3.8 vulnerabilities",
  "details": "\nIt was discovered that the urllib.request.AbstractBasicAuthHandler class \nin Python contains regex allowing for catastrophic backtracking. Specially \ncrafted traffic from a malicious HTTP server could cause a regular expression \ndenial of service (ReDoS) condition for a client.\n(CVE-2020-8492)\n\nIt was discovered that the urllib.request.AbstractBasicAuthHandler class \nin Python contains regex with a quadratic worst-case time complexity. \nSpecially crafted traffic from a malicious HTTP server could cause a regular \nexpression denial of service (ReDoS) condition for a client.\n(CVE-2021-3733)\n\nIt was discovered that the Python urllib http client could enter into an infinite \nloop when incorrectly handling certain server responses (100 Continue response). \nSpecially crafted traffic from a malicious HTTP server could cause a denial of \nservice (DoS) condition for a client.\n(CVE-2021-3737)\n\n",
  "aliases": [],
  "related": [
    "CVE-2020-8492",
    "CVE-2021-3733",
    "CVE-2021-3737"
  ],
  "published": "2021-12-17T15:59:29.220066Z",
  "modified": "2021-12-17T15:59:29.220066Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python3.8"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.8.0-3ubuntu1~18.04.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "libpython3.8-minimal": "3.8.0-3ubuntu1~18.04.2",
            "python3.8-venv": "3.8.0-3ubuntu1~18.04.2",
            "libpython3.8-stdlib": "3.8.0-3ubuntu1~18.04.2",
            "libpython3.8-dev": "3.8.0-3ubuntu1~18.04.2",
            "idle-python3.8": "3.8.0-3ubuntu1~18.04.2",
            "libpython3.8-testsuite": "3.8.0-3ubuntu1~18.04.2",
            "python3.8": "3.8.0-3ubuntu1~18.04.2",
            "python3.8-minimal": "3.8.0-3ubuntu1~18.04.2",
            "python3.8-examples": "3.8.0-3ubuntu1~18.04.2",
            "python3.8-dev": "3.8.0-3ubuntu1~18.04.2",
            "libpython3.8": "3.8.0-3ubuntu1~18.04.2"
          }
        ],
        "availability": "No subscription needed"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-5200-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2020-8492"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-3733"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-3737"
    }
  ]
}