{
  "schema_version": "1.6.3",
  "id": "USN-6630-1",
  "summary": "python-glance-store vulnerability",
  "details": "It was discovered that Glance_store incorrectly handled logging when the\nDEBUG log level is enabled. A local attacker could use this issue to obtain\naccess_key values.\n",
  "aliases": [],
  "related": [
    "CVE-2024-1141"
  ],
  "published": "2024-02-12T13:01:08.626088Z",
  "modified": "2024-02-12T13:01:08.626088Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "python-glance-store",
        "purl": "pkg:deb/ubuntu/python-glance-store@2.0.0-0ubuntu4.3?arch=src?distro=focal"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.0.0-0ubuntu4.3"
            }
          ]
        }
      ],
      "versions": [
        "1.0.0-0ubuntu1",
        "1.1.0-0ubuntu2",
        "1.1.0-0ubuntu3",
        "2.0.0-0ubuntu1",
        "2.0.0-0ubuntu2",
        "2.0.0-0ubuntu3",
        "2.0.0-0ubuntu4",
        "2.0.0-0ubuntu4.1",
        "2.0.0-0ubuntu4.2"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-glance-store-doc": "2.0.0-0ubuntu4.3",
            "python3-glance-store": "2.0.0-0ubuntu4.3"
          }
        ],
        "availability": "No subscription required"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "python-glance-store",
        "purl": "pkg:deb/ubuntu/python-glance-store@3.0.0-0ubuntu1.4?arch=src?distro=jammy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.0.0-0ubuntu1.4"
            }
          ]
        }
      ],
      "versions": [
        "2.7.0-0ubuntu1",
        "3.0.0-0ubuntu1",
        "3.0.0-0ubuntu1.1",
        "3.0.0-0ubuntu1.2",
        "3.0.0-0ubuntu1.3"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-glance-store-doc": "3.0.0-0ubuntu1.4",
            "python3-glance-store": "3.0.0-0ubuntu1.4"
          }
        ],
        "availability": "No subscription required"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:23.10",
        "name": "python-glance-store",
        "purl": "pkg:deb/ubuntu/python-glance-store@4.6.1-0ubuntu1.1?arch=src?distro=mantic"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.6.1-0ubuntu1.1"
            }
          ]
        }
      ],
      "versions": [
        "4.3.0-0ubuntu1",
        "4.3.0-0ubuntu2",
        "4.3.0-0ubuntu3",
        "4.3.0-0ubuntu4",
        "4.5.0-0ubuntu1",
        "4.6.0-0ubuntu1",
        "4.6.1-0ubuntu1"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-glance-store-doc": "4.6.1-0ubuntu1.1",
            "python3-glance-store": "4.6.1-0ubuntu1.1"
          }
        ],
        "availability": "No subscription required"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-6630-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2024-1141"
    }
  ]
}