{
  "id": "USN-4043-1",
  "summary": "python-django vulnerabilities",
  "details": "It was discovered that Django incorrectly handled certain inputs.\nAn attacker could possibly use this issue to execute arbitrary code.\nThis issue only affected Ubuntu 18.04 LTS, Ubuntu 18.10 and Ubuntu 19.04.\n(CVE-2019-12308)\n\nGavin Wahl discovered that Django incorrectly handled HTTP detection when used behind a reverse-proxy. Client requests made via HTTP would cause incorrect API results and would not be redirected to HTTPS, contrary to expectations. (CVE-2019-12781)\n",
  "aliases": [],
  "related": [
    "CVE-2019-12308",
    "CVE-2019-12781"
  ],
  "published": "2019-07-01T11:02:10.091898Z",
  "modified": "2019-07-01T11:02:10.091898Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python-django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1:1.11.11-1ubuntu1.4"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3-django": "1:1.11.11-1ubuntu1.4",
            "python-django-doc": "1:1.11.11-1ubuntu1.4",
            "python-django-common": "1:1.11.11-1ubuntu1.4",
            "python-django": "1:1.11.11-1ubuntu1.4"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS",
        "name": "python-django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.8.7-1ubuntu5.9"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3-django": "1.8.7-1ubuntu5.9",
            "python-django-doc": "1.8.7-1ubuntu5.9",
            "python-django-common": "1.8.7-1ubuntu5.9",
            "python-django": "1.8.7-1ubuntu5.9"
          }
        ],
        "availability": "No subscription needed"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-4043-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2019-12308"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2019-12781"
    }
  ]
}