{
  "id": "USN-4171-4",
  "summary": "apport regression",
  "details": "USN-4171-1 fixed a vulnerability in Apport. The update caused a regression\nin the Python Apport library. This update fixes the problem for Ubuntu 14.04 ESM.\n\nWe apologize for the inconvenience.\n\nOriginal advisory details:\n\n Kevin Backhouse discovered Apport would read its user-controlled settings\n file as the root user. This could be used by a local attacker to possibly\n crash Apport or have other unspecified consequences. (CVE-2019-11481)\n\n Sander Bos discovered a race-condition in Apport during core dump\n creation. This could be used by a local attacker to generate a crash report\n for a privileged process that is readable by an unprivileged user.\n (CVE-2019-11482)\n\n Sander Bos discovered Apport mishandled crash dumps originating from\n containers. This could be used by a local attacker to generate a crash\n report for a privileged process that is readable by an unprivileged user.\n (CVE-2019-11483)\n\n Sander Bos discovered Apport mishandled lock-file creation. This could be\n used by a local attacker to cause a denial of service against Apport.\n (CVE-2019-11485)\n\n Kevin Backhouse discovered Apport read various process-specific files with\n elevated privileges during crash dump generation. This could could be used\n by a local attacker to generate a crash report for a privileged process\n that is readable by an unprivileged user. (CVE-2019-15790)\n",
  "aliases": [],
  "related": [],
  "published": "2019-11-05T14:04:25.325382Z",
  "modified": "2019-11-05T14:04:25.325382Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:14.04:LTS",
        "name": "apport"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.14.1-0ubuntu3.29+esm3"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-apport": "2.14.1-0ubuntu3.29+esm3",
            "python3-problem-report": "2.14.1-0ubuntu3.29+esm3",
            "apport-kde": "2.14.1-0ubuntu3.29+esm3",
            "apport-retrace": "2.14.1-0ubuntu3.29+esm3",
            "apport-valgrind": "2.14.1-0ubuntu3.29+esm3",
            "python3-apport": "2.14.1-0ubuntu3.29+esm3",
            "dh-apport": "2.14.1-0ubuntu3.29+esm3",
            "apport-gtk": "2.14.1-0ubuntu3.29+esm3",
            "apport": "2.14.1-0ubuntu3.29+esm3",
            "python-problem-report": "2.14.1-0ubuntu3.29+esm3",
            "apport-noui": "2.14.1-0ubuntu3.29+esm3"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-4171-4"
    },
    {
      "type": "REPORT",
      "url": "https://launchpad.net/bugs/1850929"
    }
  ]
}