{
  "description": "Eric Soroos discovered that the Python Imaging Library incorrectly handled\ncertain malformed FLI or PhotoCD files. A remote attacker could use this\nissue to cause Python Imaging Library to crash, resulting in a denial of\nservice. (CVE-2016-0775, CVE-2016-2533)\n\nAndrew Drake discovered that the Python Imaging Libray incorrectly validated\ninput. A remote attacker could use this to cause Python Imaging Library to\ncrash, resulting in a denial of service. (CVE-2014-3589)\n",
  "releases": {
    "precise": {
      "sources": {
        "python-imaging": {
          "version": "1.1.7-4ubuntu0.12.04.2",
          "description": "Python Imaging Library"
        }
      },
      "binaries": {
        "python-imaging": {
          "version": "1.1.7-4ubuntu0.12.04.2"
        }
      },
      "archs": {
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-doc_1.1.7-4ubuntu0.12.04.2_all.deb": {
              "size": 41876,
              "md5": "65acae128eef961af3055eebbc59a795"
            }
          }
        },
        "amd64": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-tk_1.1.7-4ubuntu0.12.04.2_amd64.deb": {
              "size": 8110,
              "md5": "8f45d8bdef39510350d7c07f13513eb9"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-sane-dbg_1.1.7-4ubuntu0.12.04.2_amd64.deb": {
              "size": 43156,
              "md5": "07a55a291f597c9f659b2bc6fcc207bb"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-tk-dbg_1.1.7-4ubuntu0.12.04.2_amd64.deb": {
              "size": 14796,
              "md5": "d151db458421db2a79869a5e53e83cb4"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-dbg_1.1.7-4ubuntu0.12.04.2_amd64.deb": {
              "size": 636456,
              "md5": "7d604c5e78a236de0a417a5eeb43f980"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging_1.1.7-4ubuntu0.12.04.2_amd64.deb": {
              "size": 292700,
              "md5": "2e693cf814a797e4d2b3343726401615"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-sane_1.1.7-4ubuntu0.12.04.2_amd64.deb": {
              "size": 21272,
              "md5": "9a3e522a53b771ae50892f6402d50134"
            }
          }
        },
        "powerpc": {
          "urls": {
            "http://ports.ubuntu.com/pool/main/p/python-imaging/python-imaging-sane-dbg_1.1.7-4ubuntu0.12.04.2_powerpc.deb": {
              "size": 43104,
              "md5": "43299e71d4694cb81b09f0894a12d95a"
            },
            "http://ports.ubuntu.com/pool/main/p/python-imaging/python-imaging-tk_1.1.7-4ubuntu0.12.04.2_powerpc.deb": {
              "size": 8176,
              "md5": "b630faf5aadd7e8effcdeb2c02540361"
            },
            "http://ports.ubuntu.com/pool/main/p/python-imaging/python-imaging-sane_1.1.7-4ubuntu0.12.04.2_powerpc.deb": {
              "size": 20944,
              "md5": "8d1f5109db20051aad3e58d2b9672256"
            },
            "http://ports.ubuntu.com/pool/main/p/python-imaging/python-imaging_1.1.7-4ubuntu0.12.04.2_powerpc.deb": {
              "size": 287054,
              "md5": "8062e55495afbaff921940f0bf9b229c"
            },
            "http://ports.ubuntu.com/pool/main/p/python-imaging/python-imaging-tk-dbg_1.1.7-4ubuntu0.12.04.2_powerpc.deb": {
              "size": 15476,
              "md5": "8bb9c3308f6c61c20242bf7ac7381f25"
            },
            "http://ports.ubuntu.com/pool/main/p/python-imaging/python-imaging-dbg_1.1.7-4ubuntu0.12.04.2_powerpc.deb": {
              "size": 631330,
              "md5": "5c6bcf975a7f4a1ad0de9d9f77adad1f"
            }
          }
        },
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging_1.1.7.orig.tar.gz": {
              "size": 498749,
              "md5": "fc14a54e1ce02a0225be8854bfba478e"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging_1.1.7-4ubuntu0.12.04.2.dsc": {
              "size": 2394,
              "md5": "bcaadef8579b3abb38dca60630de4f6f"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging_1.1.7-4ubuntu0.12.04.2.diff.gz": {
              "size": 10128,
              "md5": "f1512c9558b0c9877b35f5ed570d3bb1"
            }
          }
        },
        "i386": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-sane-dbg_1.1.7-4ubuntu0.12.04.2_i386.deb": {
              "size": 41630,
              "md5": "3ca905816f32913001838dd59f5d0e1f"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-dbg_1.1.7-4ubuntu0.12.04.2_i386.deb": {
              "size": 607630,
              "md5": "2dfab4d76de254093be587f76f831dc2"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-sane_1.1.7-4ubuntu0.12.04.2_i386.deb": {
              "size": 21242,
              "md5": "f2cb156d2d63d6c4b3a7eefaf3399123"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging_1.1.7-4ubuntu0.12.04.2_i386.deb": {
              "size": 293246,
              "md5": "8057a6dcde20271e1610037a911f72b8"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-tk-dbg_1.1.7-4ubuntu0.12.04.2_i386.deb": {
              "size": 14642,
              "md5": "b183673fc3445d56220f5a15c97ede09"
            },
            "http://security.ubuntu.com/ubuntu/pool/main/p/python-imaging/python-imaging-tk_1.1.7-4ubuntu0.12.04.2_i386.deb": {
              "size": 8168,
              "md5": "a6778017502308d6b73dcd14d99943d7"
            }
          }
        },
        "armel": {
          "urls": {
            "http://ports.ubuntu.com/pool/": {
              "size": 7632,
              "md5": "1b69842439847463ef10eaf6df9634b7"
            }
          }
        },
        "armhf": {
          "urls": {
            "http://ports.ubuntu.com/pool/": {
              "size": 7638,
              "md5": "1da26e81f85a519a562d228c45ceff8f"
            }
          }
        }
      }
    }
  },
  "title": "Python Imaging Library vulnerabilities",
  "timestamp": 1473949576.445847,
  "summary": "python-imaging vulnerabilities",
  "action": "In general, a standard system update will make all the necessary changes.\n",
  "cves": [
    "CVE-2014-3589",
    "CVE-2016-0775",
    "CVE-2016-2533"
  ],
  "id": "USN-3080-1",
  "isummary": "Python Imaging Libary could be made to crash if it received specially crafted\ninput or opened a specially crafted file.\n"
}