{
  "description": "Gabriel Corona discovered that RDFLib did not properly load modules on the\ncommand-line. An attacker could possibly use this issue to cause RDFLib to\nexecute arbitrary code. (CVE-2019-7653)\n",
  "releases": {
    "xenial": {
      "allbinaries": {
        "python3-rdflib": {
          "pocket": "security",
          "version": "4.1.2-3+deb8u1build0.16.04.1"
        },
        "python-rdflib-doc": {
          "pocket": "security",
          "version": "4.1.2-3+deb8u1build0.16.04.1"
        },
        "python-rdflib-tools": {
          "pocket": "security",
          "version": "4.1.2-3+deb8u1build0.16.04.1"
        },
        "python-rdflib": {
          "pocket": "security",
          "version": "4.1.2-3+deb8u1build0.16.04.1"
        }
      },
      "binaries": {
        "python3-rdflib": {
          "pocket": "security",
          "version": "4.1.2-3+deb8u1build0.16.04.1"
        },
        "python-rdflib-tools": {
          "pocket": "security",
          "version": "4.1.2-3+deb8u1build0.16.04.1"
        },
        "python-rdflib": {
          "pocket": "security",
          "version": "4.1.2-3+deb8u1build0.16.04.1"
        }
      },
      "archs": {
        "all": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/python-rdflib-doc_4.1.2-3+deb8u1build0.16.04.1_all.deb": {
              "md5": "de23e99e3c196d36cacf726b067ca97c",
              "size": 575158
            }
          }
        },
        "amd64": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/python-rdflib-tools_4.1.2-3+deb8u1build0.16.04.1_amd64.deb": {
              "md5": "88f8dbbd555a61a56086f015bae52c58",
              "size": 9186
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/python3-rdflib_4.1.2-3+deb8u1build0.16.04.1_amd64.deb": {
              "md5": "2a3b3b3da892899f383422035f34a282",
              "size": 228398
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/python-rdflib_4.1.2-3+deb8u1build0.16.04.1_amd64.deb": {
              "md5": "2c047edb4eba178ed5312c78d71aa884",
              "size": 229376
            }
          }
        },
        "ppc64el": {
          "urls": {
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib_4.1.2-3+deb8u1build0.16.04.1_ppc64el.deb": {
              "md5": "52e91896b13b892d5241a857e09ec154",
              "size": 229250
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python3-rdflib_4.1.2-3+deb8u1build0.16.04.1_ppc64el.deb": {
              "md5": "9fb9c53134d50e31b285122c39bdb921",
              "size": 228276
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib-tools_4.1.2-3+deb8u1build0.16.04.1_ppc64el.deb": {
              "md5": "2e300924ec6a6cc6c18a0555d03006e3",
              "size": 9214
            }
          }
        },
        "i386": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/python-rdflib-tools_4.1.2-3+deb8u1build0.16.04.1_i386.deb": {
              "md5": "fc2e9c9eb968f664feb680cb2167f177",
              "size": 9180
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/python-rdflib_4.1.2-3+deb8u1build0.16.04.1_i386.deb": {
              "md5": "9685d55cba1d25917e01a6c39833937b",
              "size": 229394
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/python3-rdflib_4.1.2-3+deb8u1build0.16.04.1_i386.deb": {
              "md5": "33eb39ba03a6b18d35da5dc8e8f2fc76",
              "size": 228374
            }
          }
        },
        "powerpc": {
          "urls": {
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib-tools_4.1.2-3+deb8u1build0.16.04.1_powerpc.deb": {
              "md5": "1d487d140b8c5c8490d8af6db3f884a7",
              "size": 9190
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib_4.1.2-3+deb8u1build0.16.04.1_powerpc.deb": {
              "md5": "8da56829c690a2a4734cd42407040438",
              "size": 229528
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python3-rdflib_4.1.2-3+deb8u1build0.16.04.1_powerpc.deb": {
              "md5": "ec763fe6be88cf0c6a5d5f2e04efe9a5",
              "size": 228486
            }
          }
        },
        "source": {
          "urls": {
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/rdflib_4.1.2-3+deb8u1build0.16.04.1.debian.tar.xz": {
              "md5": "cb553cf325b197ee21409d224c7f512f",
              "size": 27864
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/rdflib_4.1.2-3+deb8u1build0.16.04.1.dsc": {
              "md5": "caa261c8f8f3b66b426be8a1ab85625c",
              "size": 2516
            },
            "http://security.ubuntu.com/ubuntu/pool/universe/r/rdflib/rdflib_4.1.2.orig.tar.gz": {
              "md5": "5c284061f1f2a086b0782644afbaac59",
              "size": 894937
            }
          }
        },
        "s390x": {
          "urls": {
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib_4.1.2-3+deb8u1build0.16.04.1_s390x.deb": {
              "md5": "56e152f5266c3fc2000da95657a7ba5d",
              "size": 229352
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib-tools_4.1.2-3+deb8u1build0.16.04.1_s390x.deb": {
              "md5": "11d1f38d69d5705ac51949864c42c1d5",
              "size": 9222
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python3-rdflib_4.1.2-3+deb8u1build0.16.04.1_s390x.deb": {
              "md5": "0e1a50f80411d74d8103f08b20abb3c1",
              "size": 228378
            }
          }
        },
        "armhf": {
          "urls": {
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib_4.1.2-3+deb8u1build0.16.04.1_armhf.deb": {
              "md5": "72014d70cea50465fbdca00b53b17ab0",
              "size": 229774
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python3-rdflib_4.1.2-3+deb8u1build0.16.04.1_armhf.deb": {
              "md5": "a852843aa927e7c505442ad89e14dec4",
              "size": 228834
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib-tools_4.1.2-3+deb8u1build0.16.04.1_armhf.deb": {
              "md5": "a5e1145ee7ea0200ffdbc784eced0718",
              "size": 9192
            }
          }
        },
        "arm64": {
          "urls": {
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python3-rdflib_4.1.2-3+deb8u1build0.16.04.1_arm64.deb": {
              "md5": "6af415151b3efc8a2224b1f1bdebbd01",
              "size": 228762
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib_4.1.2-3+deb8u1build0.16.04.1_arm64.deb": {
              "md5": "a91b35502f699a19328463972a1976ce",
              "size": 229748
            },
            "http://ports.ubuntu.com/pool/universe/r/rdflib/python-rdflib-tools_4.1.2-3+deb8u1build0.16.04.1_arm64.deb": {
              "md5": "543290f1a2ac2b0b320ec2312fc89e6c",
              "size": 9198
            }
          }
        }
      },
      "sources": {
        "rdflib": {
          "version": "4.1.2-3+deb8u1build0.16.04.1",
          "description": "Pure Python package for working with RDF"
        }
      }
    }
  },
  "title": " RDFLib vulnerability",
  "timestamp": 1600879720.956284,
  "summary": "rdflib vulnerability",
  "action": "After a standard system update you need to restart any applications that\nmake use of RDFLib to make all the necessary changes.\n",
  "isummary": "RDFLib could be made to made to execute arbitrary code if it were running\nin a directory with a specially crafted file.\n",
  "id": "USN-4535-1",
  "cves": [
    "CVE-2019-7653"
  ]
}