{
  "schema_version": "1.6.3",
  "id": "UBUNTU-CVE-2019-3498",
  "details": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.",
  "aliases": [],
  "related": [
    "CVE-2019-3498",
    "USN-3851-1"
  ],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N"
    }
  ],
  "published": "2019-01-07T00:00:00Z",
  "modified": "2025-01-13T10:21:52Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:14.04:LTS",
        "name": "python-django",
        "purl": "pkg:deb/ubuntu/python-django@1.6.11-0ubuntu1.3?arch=source&distro=trusty"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.6.11-0ubuntu1.3"
            }
          ]
        }
      ],
      "versions": [
        "1.5.4-1ubuntu1",
        "1.6-1",
        "1.6.1-1",
        "1.6.1-2",
        "1.6.1-2ubuntu0.1",
        "1.6.1-2ubuntu0.2",
        "1.6.1-2ubuntu0.3",
        "1.6.1-2ubuntu0.4",
        "1.6.1-2ubuntu0.5",
        "1.6.1-2ubuntu0.6",
        "1.6.1-2ubuntu0.8",
        "1.6.1-2ubuntu0.9",
        "1.6.1-2ubuntu0.10",
        "1.6.1-2ubuntu0.11",
        "1.6.1-2ubuntu0.12",
        "1.6.1-2ubuntu0.13",
        "1.6.1-2ubuntu0.14",
        "1.6.1-2ubuntu0.15",
        "1.6.1-2ubuntu0.16",
        "1.6.11-0ubuntu1",
        "1.6.11-0ubuntu1.1",
        "1.6.11-0ubuntu1.2"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "binary_name": "python-django",
            "binary_version": "1.6.11-0ubuntu1.3"
          },
          {
            "binary_name": "python-django-doc",
            "binary_version": "1.6.11-0ubuntu1.3"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "medium"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS",
        "name": "python-django",
        "purl": "pkg:deb/ubuntu/python-django@1.8.7-1ubuntu5.7?arch=source&distro=xenial"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.8.7-1ubuntu5.7"
            }
          ]
        }
      ],
      "versions": [
        "1.7.9-1ubuntu5",
        "1.8.5-2ubuntu1",
        "1.8.7-1ubuntu1",
        "1.8.7-1ubuntu2",
        "1.8.7-1ubuntu3",
        "1.8.7-1ubuntu4",
        "1.8.7-1ubuntu5",
        "1.8.7-1ubuntu5.1",
        "1.8.7-1ubuntu5.2",
        "1.8.7-1ubuntu5.4",
        "1.8.7-1ubuntu5.5",
        "1.8.7-1ubuntu5.6"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "binary_name": "python-django",
            "binary_version": "1.8.7-1ubuntu5.7"
          },
          {
            "binary_name": "python-django-common",
            "binary_version": "1.8.7-1ubuntu5.7"
          },
          {
            "binary_name": "python-django-doc",
            "binary_version": "1.8.7-1ubuntu5.7"
          },
          {
            "binary_name": "python3-django",
            "binary_version": "1.8.7-1ubuntu5.7"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "medium"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python-django",
        "purl": "pkg:deb/ubuntu/python-django@1:1.11.11-1ubuntu1.2?arch=source&distro=bionic"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1:1.11.11-1ubuntu1.2"
            }
          ]
        }
      ],
      "versions": [
        "1:1.11.4-1ubuntu1",
        "1:1.11.6-1ubuntu1",
        "1:1.11.9-1ubuntu1",
        "1:1.11.11-1ubuntu1",
        "1:1.11.11-1ubuntu1.1"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "binary_name": "python-django",
            "binary_version": "1:1.11.11-1ubuntu1.2"
          },
          {
            "binary_name": "python-django-common",
            "binary_version": "1:1.11.11-1ubuntu1.2"
          },
          {
            "binary_name": "python-django-doc",
            "binary_version": "1:1.11.11-1ubuntu1.2"
          },
          {
            "binary_name": "python3-django",
            "binary_version": "1:1.11.11-1ubuntu1.2"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "medium"
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2019-3498"
    },
    {
      "type": "REPORT",
      "url": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-3851-1"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2019-3498"
    }
  ]
}