{
  "schema_version": "1.7.0",
  "id": "UBUNTU-CVE-2025-55552",
  "details": "pytorch v2.8.0 was discovered to display unexpected behavior when the components torch.rot90 and torch.randn_like are used together.",
  "aliases": [],
  "upstream": [
    "CVE-2025-55552"
  ],
  "related": [],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
    },
    {
      "type": "Ubuntu",
      "score": "medium"
    }
  ],
  "published": "2025-09-25T16:15:00Z",
  "modified": "2025-10-02T05:23:28Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "pytorch",
        "purl": "pkg:deb/ubuntu/pytorch@1.8.1-4?arch=source&distro=jammy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "1.7.1-7",
        "1.8.1-4"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "binary_name": "libtorch-dev",
            "binary_version": "1.8.1-4"
          },
          {
            "binary_name": "libtorch-test",
            "binary_version": "1.8.1-4"
          },
          {
            "binary_name": "libtorch1.8",
            "binary_version": "1.8.1-4"
          },
          {
            "binary_name": "python3-torch",
            "binary_version": "1.8.1-4"
          }
        ]
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:25.04",
        "name": "pytorch",
        "purl": "pkg:deb/ubuntu/pytorch@2.6.0+dfsg-5build1?arch=source&distro=plucky"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "2.4.1-1ubuntu1",
        "2.4.1-1ubuntu3",
        "2.5.1+dfsg-3",
        "2.5.1+dfsg-4build1",
        "2.5.1+dfsg-4build2",
        "2.6.0+dfsg-3",
        "2.6.0+dfsg-4",
        "2.6.0+dfsg-5",
        "2.6.0+dfsg-5build1"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "binary_name": "libtorch-dev",
            "binary_version": "2.6.0+dfsg-5build1"
          },
          {
            "binary_name": "libtorch-test",
            "binary_version": "2.6.0+dfsg-5build1"
          },
          {
            "binary_name": "libtorch2.6",
            "binary_version": "2.6.0+dfsg-5build1"
          },
          {
            "binary_name": "python3-torch",
            "binary_version": "2.6.0+dfsg-5build1"
          }
        ]
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2025-55552"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2025-55552"
    },
    {
      "type": "REPORT",
      "url": "https://gist.github.com/shaoyuyoung/0e7d2a586297ae9c8ed14d8706749efc"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/pytorch/pytorch/issues/147847"
    }
  ]
}