{
  "schema_version": "1.7.0",
  "id": "UBUNTU-CVE-2025-8283",
  "details": "A vulnerability was found in the netavark package, a network stack for containers used with Podman. Due to dns.podman search domain being removed, netavark may return external servers if a valid A/AAAA record is sent as a response. When creating a container with a given name, this name will be used as the hostname for the container itself, as the podman's search domain is not added anymore the container is using the host's resolv.conf, and the DNS resolver will try to look into the search domains contained on it. If one of the domains contain a name with the same hostname as the running container, the connection will forward to unexpected external servers.",
  "aliases": [],
  "upstream": [
    "CVE-2025-8283"
  ],
  "related": [],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N"
    },
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N"
    },
    {
      "type": "Ubuntu",
      "score": "medium"
    }
  ],
  "published": "2025-07-28T19:15:00Z",
  "modified": "2025-08-14T04:55:46Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:24.04:LTS",
        "name": "netavark",
        "purl": "pkg:deb/ubuntu/netavark@1.4.0-4?arch=source&distro=noble"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "1.4.0-3",
        "1.4.0-4"
      ],
      "ecosystem_specific": {}
    },
    {
      "package": {
        "ecosystem": "Ubuntu:25.04",
        "name": "netavark",
        "purl": "pkg:deb/ubuntu/netavark@1.12.1-9?arch=source&distro=plucky"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "1.9.0-4",
        "1.12.1-5",
        "1.12.1-7",
        "1.12.1-9"
      ],
      "ecosystem_specific": {}
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2025-8283"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2025-8283"
    },
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2383941"
    },
    {
      "type": "REPORT",
      "url": "https://access.redhat.com/security/cve/CVE-2025-8283"
    }
  ]
}