{
    "metadata": {
        "@context": "https://openvex.dev/ns/v0.2.0",
        "@id": "https://github.com/canonical/ubuntu-security-notices/blob/main/vex/usn/USN-2469-1",
        "author": "Canonical Ltd.",
        "timestamp": "2025-01-13T11:52:36.333572",
        "version": 2
    },
    "statements": [
        {
            "vulnerability": {
                "@id": "https://ubuntu.com/security/notices/USN-2469-1",
                "name": "USN-2469-1",
                "description": "Jedediah Smith discovered that Django incorrectly handled underscores in WSGI headers. A remote attacker could possibly use this issue to spoof headers in certain environments. (CVE-2015-0219)  Mikko Ohtamaa discovered that Django incorrectly handled user-supplied redirect URLs. A remote attacker could possibly use this issue to perform a cross-site scripting attack. (CVE-2015-0220)  Alex Gaynor discovered that Django incorrectly handled reading files in django.views.static.serve(). A remote attacker could possibly use this issue to cause Django to consume resources, resulting in a denial of service. (CVE-2015-0221)  Keryn Knight discovered that Django incorrectly handled forms with ModelMultipleChoiceField. A remote attacker could possibly use this issue to cause a large number of SQL queries, resulting in a database denial of service. This issue only affected Ubuntu 14.04 LTS and Ubuntu 14.10. (CVE-2015-0222)",
                "aliases": [
                    "CVE-2015-0219",
                    "CVE-2015-0220",
                    "CVE-2015-0221",
                    "CVE-2015-0222"
                ]
            },
            "timestamp": "2015-01-13 19:40:45.491693",
            "products": [
                {
                    "@id": "pkg:deb/ubuntu/python-django@1.6.1-2ubuntu0.6?arch=source&distro=trusty"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django@1.6.1-2ubuntu0.6?arch=amd64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django@1.6.1-2ubuntu0.6?arch=arm64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django@1.6.1-2ubuntu0.6?arch=armhf"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django@1.6.1-2ubuntu0.6?arch=i386"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django@1.6.1-2ubuntu0.6?arch=powerpc"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django@1.6.1-2ubuntu0.6?arch=ppc64el"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django-doc@1.6.1-2ubuntu0.6?arch=amd64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django-doc@1.6.1-2ubuntu0.6?arch=arm64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django-doc@1.6.1-2ubuntu0.6?arch=armhf"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django-doc@1.6.1-2ubuntu0.6?arch=i386"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django-doc@1.6.1-2ubuntu0.6?arch=powerpc"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-django-doc@1.6.1-2ubuntu0.6?arch=ppc64el"
                }
            ],
            "status": "fixed",
            "status_notes": "Several security issues were fixed in Django."
        }
    ]
}